=== Aitslab/BioNLP/jacob/BioGPT/data/BC5CDR/raw/BC5CDR_Evaluation-0.0.3/BioC.dtd
<!-- BioC.dtd -->

<!--

    BioC is designed to allow programs that process text and
    annotations on that text to easily share data and work
    together. This DTD describes how that data is represented in XML
    files.

    Some believe XML is easily read by humans and that should be
    supported by clearly formatting the elements. In the long run,
    this is distracting. While the only meaningful spaces are in text
    elements and the other spaces can be ignored, current tools add no
    additional space.  Formatters and editors may be used to make the
    XML file appear more readable.

    The possible variety of annotations that one might want to produce
    or use is nearly countless. There is no guarantee that these are
    organized in the nice nested structure required for XML
    elements. Even if they were, it would be nice to easily ignore
    unwanted annotations.  So annotations are recorded in a stand off
    manner, external to the annotated text. The exceptions are
    passages and sentences because of their fundamental place in text.

    The text is expected to be encoded in Unicode, specifically
    UTF-8. This is one of the encodings required to be implemented by
    XML tools, is portable between big-endian and little-endian
    machines and is a superset of 7-bit ASCII. Code points beyond 127
    may be expressed directly in UTF-8 or indirectly using numeric
    entities.  Since many tools today still only directly process
    ASCII characters, conversion should be available and
    standardized.  Offsets should be in 8 bit code units (bytes) for
    easier processing by naive programs.

    collection:  Group of documents, usually from a larger corpus. If
    a group of documents is from several corpora, use several
    collections.

    source:  Name of the source corpus from which the documents were selected

    date:  Date documents extracted from original source. Can be as
    simple as yyyymmdd or an ISO timestamp.

    key: Separate file describing the infons used and any other useful
    information about the data in the file. For example, if a file
    includes part-of-speech tags, this file should describe the set of
    part-of-speech tags used.

    infon: key-value pairs. Can record essentially arbitrary
    information. "type" will be a particular common key in the major
    sub elements below. For PubMed references, passage "type" might
    signal "title" or "abstract". For annotations, it might indicate
    "noun phrase", "gene", or "disease". In the programming language
    data structures, infons are typically represented as a map from a
    string to a string.  This means keys should be unique within each
    parent element.

    document: A document in the collection. A single, complete
    stand-alone document as described by its parent source.

    id:  Typically, the id of the document in the parent
    source. Should at least be unique in the collection.

    passage: One portion of the document.  In the sample collection of
    PubMed documents, each document has a title and frequently an
    abstract. Structured abstracts could have additional passages. For
    a full text document, passages could be sections such as
    Introduction, Materials and Methods, or Conclusion. Another option
    would be paragraphs. Passages impose a linear structure on the
    document. Further structure in the document can be described by
    infon values.

    offset: Where the passage occurs in the parent document. Depending
    on the source corpus, this might be a very relevant number.  They
    should be sequential and identify a passage's position in the
    document.  Since the sample PubMed collection is extracted from an
    XML file, literal offsets have little value. The title is given an
    offset of zero, while the abstract is assumed to begin after the
    title and one space.

    text: The original text of the passage.

    sentence:  One sentence of the passage.

    offset: A document offset to where the sentence begins in the
    passage. This value is the sum of the passage offset and the local
    offset within the passage.

    text: The original text of the sentence.

    annotation:  Stand-off annotation

    id: Used to refer to this annotation in relations. Should be
    unique at whatever level relations at appear. If relations appear
    at the sentence level, annotation ids need to be unique within
    each sentence. Similarly, if relations appear at the passage
    level, annotation ids need to be unique within each passage.

    location: Location of the annotated text. Multiple locations
    indicate a multi-span annotation.

    offset: Document offset to where the annotated text begins in
    the passage or sentence. The value is the sum of the passage or
    sentence offset and the local offset within the passage or
    sentence.

    length: Length of the annotated text. While unlikely, this could
    be zero to describe an annotation that belongs between two
    characters.

    text:  Typically the annotated text.

    relation: Relation between multiple annotations and / or other
    relations. Relations are allowed to appear at several levels
    (document, passage, and sentence). Typically they will all appear
    at one level, the level at which they are determined.
    Significantly different types of relations might appear at
    different levels.

    id: Used to refer to this relation in other relations. This id
    needs to be unique at whatever level relations appear. (See
    discussion of annotation ids.)

    refid: Id of an annotation or an other relation.

    role: Describes how the referenced annotattion or other relation
    participates in the current relation. Has a default value so it
    can be left out if there is no meaningful value.

-->

<!ELEMENT collection ( source, date, key, infon*, document+ ) >
<!ELEMENT source (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT infon (#PCDATA)>
<!ATTLIST infon key CDATA #REQUIRED >

<!ELEMENT document ( id, infon*, passage+, relation* ) >
<!ELEMENT id (#PCDATA)>

<!ELEMENT passage ( infon*, offset, ( ( text?, annotation* ) | sentence* ), relation* ) >
<!ELEMENT offset (#PCDATA)>
<!ELEMENT text (#PCDATA)>

<!ELEMENT sentence ( infon*, offset, text?, annotation*, relation* ) >

<!ELEMENT annotation ( infon*, location*, text ) >
<!ATTLIST annotation id CDATA #IMPLIED >
<!ELEMENT location EMPTY>
<!ATTLIST location offset CDATA #REQUIRED >
<!ATTLIST location length CDATA #REQUIRED >

<!ELEMENT relation ( infon*, node* ) >
<!ATTLIST relation id CDATA #IMPLIED >
<!ELEMENT node EMPTY>
<!ATTLIST node refid CDATA #REQUIRED >
<!ATTLIST node role CDATA "" >

=== Aitslab/BioNLP/jacob/BioGPT/data/BC5CDR/raw/BC5CDR_Evaluation-0.0.3/data/test/CDR_sample.test.DNER.BioC.xml
<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE collection SYSTEM 'BioC.dtd'>
<collection>
<source>PubTator</source>
<date>0/0/0</date>
<key>PubTator.key</key>
<document>
<id>26094</id>
<passage>
<infon key="type">title</infon>
<offset>0</offset>
<text>Antihypertensive drugs and depression: a reappraisal.</text>
<annotation id='1'>
<infon key="type">Disease</infon>
<infon key='MESH'>D003866</infon>
<infon key="score">0.792633056640625</infon>
<location offset='27' length='10' />
<text>depression</text>
</annotation>
</passage>
<passage>
<infon key="type">abstract</infon>
<offset>54</offset>
<text>Eighty-nine new referral hypertensive out-patients and 46 new referral non-hypertensive chronically physically ill out-patients completed a mood rating scale at regular intervals for one year. The results showed a high prevalence of depression in both groups of patients, with no preponderance in the hypertensive group. Hypertensive patients with psychiatric histories had a higher prevalence of depression than the comparison patients. This was accounted for by a significant number of depressions occurring in methyl dopa treated patients with psychiatric histories.</text>
<annotation id='2'>
<infon key="type">Disease</infon>
<infon key='MESH'>D006973</infon>
<infon key="score">0.47882080078125</infon>
<location offset='79' length='12' />
<text>hypertensive</text>
</annotation>
<annotation id='3'>
<infon key="type">Disease</infon>
<infon key='MESH'>D006973</infon>
<infon key="score">0.47882080078125</infon>
<location offset='129' length='12' />
<text>hypertensive</text>
</annotation>
<annotation id='4'>
<infon key="type">Disease</infon>
<infon key='MESH'>D003866</infon>
<infon key="score">0.792633056640625</infon>
<location offset='287' length='10' />
<text>depression</text>
</annotation>
<annotation id='5'>
<infon key="type">Disease</infon>
<infon key='MESH'>D006973</infon>
<infon key="score">0.47882080078125</infon>
<location offset='355' length='12' />
<text>hypertensive</text>
</annotation>
<annotation id='6'>
<infon key="type">Disease</infon>
<infon key='MESH'>D006973</infon>
<infon key="score">0.47882080078125</infon>
<location offset='375' length='12' />
<text>Hypertensive</text>
</annotation>
<annotation id='7'>
<infon key="type">Disease</infon>
<infon key='MESH'>D003866</infon>
<infon key="score">0.792633056640625</infon>
<location offset='451' length='10' />
<text>depression</text>
</annotation>
<annotation id='8'>
<infon key="type">Disease</infon>
<infon key='MESH'>D003866</infon>
<infon key="score">0.792633056640625</infon>
<location offset='542' length='11' />
<text>depressions</text>
</annotation>
</passage>
</document>
<document>
<id>354896</id>
<passage>
<infon key="type">title</infon>
<offset>0</offset>
<text>Lidocaine-induced cardiac asystole.</text>
<annotation id='3'>
<infon key="type">Disease</infon>
<infon key='MESH'>D006331</infon>
<infon key="score">0.93243408203125</infon>
<location offset='18' length='16' />
<text>cardiac asystole</text>
</annotation>
</passage>
<passage>
<infon key="type">abstract</infon>
<offset>36</offset>
<text>Intravenous administration of a single 50-mg bolus of lidocaine in a 67-year-old man resulted in profound depression of the activity of the sinoatrial and atrioventricular nodal pacemakers. The patient had no apparent associated conditions which might have predisposed him to the development of bradyarrhythmias; and, thus, this probably represented a true idiosyncrasy to lidocaine.</text>
<annotation id='4'>
<infon key="type">Disease</infon>
<infon key='MESH'>D003866</infon>
<infon key="score">0.792633056640625</infon>
<location offset='142' length='10' />
<text>depression</text>
</annotation>
<annotation id='5'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009135</infon>
<infon key="score">0.36505126953125</infon>
<location offset='265' length='10' />
<text>conditions</text>
</annotation>
<annotation id='6'>
<infon key="type">Disease</infon>
<infon key='MESH'>D001919</infon>
<infon key="score">0.7236328125</infon>
<location offset='331' length='16' />
<text>bradyarrhythmias</text>
</annotation>
</passage>
</document>
<document>
<id>1720453</id>
<passage>
<infon key="type">title</infon>
<offset>0</offset>
<text>Long-term follow-up of ifosfamide renal toxicity in children treated for malignant mesenchymal tumors: an International Society of Pediatric Oncology report.</text>
<annotation id='12'>
<infon key="type">Disease</infon>
<infon key='MESH'>D007674</infon>
<infon key="score">0.369049072265625</infon>
<location offset='34' length='14' />
<text>renal toxicity</text>
</annotation>
<annotation id='13'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='83' length='18' />
<text>mesenchymal tumors</text>
</annotation>
</passage>
<passage>
<infon key="type">abstract</infon>
<offset>158</offset>
<text>The renal function of 74 children with malignant mesenchymal tumors in complete remission and who have received the same ifosfamide chemotherapy protocol (International Society of Pediatric Oncology Malignant Mesenchymal Tumor Study 84 [SIOP MMT 84]) were studied 1 year after the completion of treatment. Total cumulative doses were 36 or 60 g/m2 of ifosfamide (six or 10 cycles of ifosfamide, vincristine, and dactinomycin [IVA]). None of them had received cisplatin chemotherapy. Ages ranged from 4 months to 17 years; 58 patients were males and 42 females. The most common primary tumor site was the head and neck. Renal function was investigated by measuring plasma and urinary electrolytes, glucosuria, proteinuria, aminoaciduria, urinary pH, osmolarity, creatinine clearance, phosphate tubular reabsorption, beta 2 microglobulinuria, and lysozymuria. Fifty-eight patients (78%) had normal renal tests, whereas 16 patients (22%) had renal abnormalities. Two subsets of patients were identified from this latter group: the first included four patients (5% of the total population) who developed major toxicity resulting in Fanconi&apos;s syndrome (TDFS); and the second group included five patients with elevated beta 2 microglobulinuria and low phosphate reabsorption. The remaining seven patients had isolated beta 2 microglobulinuria. Severe toxicity was correlated with the higher cumulative dose of 60 g/m2 of ifosfamide, a younger age (less than 2 1/2 years old), and a predominance of vesicoprostatic tumor involvement. This low percentage (5%) of TDFS must be evaluated with respect to the efficacy of ifosfamide in the treatment of mesenchymal tumors in children.</text>
<annotation id='14'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='207' length='18' />
<text>mesenchymal tumors</text>
</annotation>
<annotation id='15'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='379' length='5' />
<text>Tumor</text>
</annotation>
<annotation id='16'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='743' length='5' />
<text>tumor</text>
</annotation>
<annotation id='17'>
<infon key="type">Disease</infon>
<infon key='MESH'>D011507</infon>
<infon key="score">0.045166015625</infon>
<location offset='867' length='11' />
<text>proteinuria</text>
</annotation>
<annotation id='18'>
<infon key="type">Disease</infon>
<infon key='MESH'>D000608</infon>
<infon key="score">0.47625732421875</infon>
<location offset='880' length='13' />
<text>aminoaciduria</text>
</annotation>
<annotation id='19'>
<infon key="type">Disease</infon>
<infon key='MESH'>D007674</infon>
<infon key="score">0.369049072265625</infon>
<location offset='1097' length='19' />
<text>renal abnormalities</text>
</annotation>
<annotation id='20'>
<infon key="type">Disease</infon>
<infon key='MESH'>D014786</infon>
<infon key="score">0.841217041015625</infon>
<location offset='1264' length='8' />
<text>toxicity</text>
</annotation>
<annotation id='21'>
<infon key="type">Disease</infon>
<infon key='MESH'>D005199</infon>
<infon key="score">0.649993896484375</infon>
<location offset='1286' length='18' />
<text>Fanconi&apos;s syndrome</text>
</annotation>
<annotation id='22'>
<infon key="type">Disease</infon>
<infon key='MESH'>D014786</infon>
<infon key="score">0.841217041015625</infon>
<location offset='1503' length='8' />
<text>toxicity</text>
</annotation>
<annotation id='23'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='1666' length='5' />
<text>tumor</text>
</annotation>
<annotation id='24'>
<infon key="type">Disease</infon>
<infon key='MESH'>D009369</infon>
<infon key="score">0.31304931640625</infon>
<location offset='1799' length='18' />
<text>mesenchymal tumors</text>
</annotation>
</passage>
</document>
<document>
<id>2224762</id>
<passage>
<infon key="type">title</infon>
<offset>0</offset>
<text>A phase I study of 4&apos;-0-tetrahydropyranyladriamycin. Clinical pharmacology and pharmacokinetics.</text>
</passage>
<passage>
<infon key="type">abstract</infon>
<offset>102</offset>
